-- ============================================================================
-- Migration 001: mass_notifications schema
-- Database: landing_member_support_db (Railway Postgres)
--
-- This schema stores the audit trail for the Mass Notifications system.
-- It replaces two Google Sheets mechanisms:
--   1. Hidden "Archive_*" sheets (recipient snapshots per campaign)
--   2. The RowStates JSON column in Run_Log (per-recipient send state)
--
-- The Run_Log sheet itself is NOT replaced — it continues to exist in
-- the spreadsheet for restoreRecipientsFromRow() and undo functionality.
-- This DB is the long-term archive and source of truth for historical data.
-- ============================================================================

-- Create the schema (like a folder that groups related tables)
CREATE SCHEMA IF NOT EXISTS mass_notifications;

-- ── campaigns ────────────────────────────────────────────────────────────────
-- One row per send operation. Maps to a Run_Log row in the spreadsheet.
--
-- Key concepts:
--   SERIAL      = auto-incrementing integer (Postgres assigns 1, 2, 3, …)
--   PRIMARY KEY = unique row identifier, never duplicates, never null
--   TIMESTAMPTZ = timestamp stored in UTC, displayed in your local timezone
--   NOT NULL    = this column must always have a value
--   DEFAULT     = value used if you don't provide one on insert

CREATE TABLE mass_notifications.campaigns (
    id              SERIAL PRIMARY KEY,

    -- The run ID generated by Apps Script (e.g., "SEND_INDIVIDUAL-20260316_143022")
    run_id          TEXT NOT NULL UNIQUE,

    -- SEND_INDIVIDUAL, SEND_BCC, DRYRUN_DRAFTS, UNDO
    mode            TEXT NOT NULL,

    -- Name of the recipients sheet used for this campaign
    recipients_sheet TEXT NOT NULL,

    -- How many emails were actually sent (excludes skipped rows)
    emails_sent     INTEGER NOT NULL DEFAULT 0,

    -- Total rows in the recipients sheet at time of send (sent + skipped)
    total_rows      INTEGER NOT NULL DEFAULT 0,

    -- Email of the person who triggered the send
    actor           TEXT NOT NULL,

    -- The resolved subject line (truncated to 180 chars, same as Run_Log)
    subject         TEXT,

    -- Full config snapshot as JSON — same blob stored in Run_Log column H
    config_snapshot JSONB,

    -- Freeform notes (error messages, etc.)
    notes           TEXT,

    -- Did the run complete successfully?
    completed       BOOLEAN NOT NULL DEFAULT FALSE,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── recipients ───────────────────────────────────────────────────────────────
-- One row per recipient per campaign. Logs EVERY row from the recipients sheet,
-- whether the email was sent or skipped.
--
-- Key concepts:
--   FOREIGN KEY = this column must reference an existing campaign id.
--                 If you try to insert a recipient pointing to a campaign
--                 that doesn't exist, Postgres will reject it.
--   ON DELETE CASCADE = if a campaign row is deleted, all its recipients
--                       are automatically deleted too (keeps data consistent).

CREATE TABLE mass_notifications.recipients (
    id              SERIAL PRIMARY KEY,

    -- Links this recipient to a campaign
    -- REFERENCES = foreign key constraint (must match a campaigns.id value)
    campaign_id     INTEGER NOT NULL
                    REFERENCES mass_notifications.campaigns(id)
                    ON DELETE CASCADE,

    -- Row number in the original spreadsheet (useful for reconciliation)
    sheet_row       INTEGER,

    email           TEXT NOT NULL,
    name            TEXT,
    unit            TEXT,

    -- Status BEFORE the send: blank, PENDING, READY, SKIP, SENT, etc.
    status_before   TEXT,

    -- Status AFTER the send: SENT, SKIP, ERROR, etc.
    status_after    TEXT,

    -- When the email was last sent (before this run) — nullable
    last_sent_before TIMESTAMPTZ,

    -- When the email was sent in this run — nullable (null if skipped)
    last_sent_after  TIMESTAMPTZ,

    -- Per-recipient notes (e.g., "skipped: no valid email")
    notes           TEXT
);

-- ── Indexes ──────────────────────────────────────────────────────────────────
-- Indexes speed up queries on columns you search/filter by frequently.
-- Think of them like a book's index — Postgres can jump straight to matching
-- rows instead of scanning every row in the table.

-- Find all recipients for a given campaign
CREATE INDEX idx_recipients_campaign_id
    ON mass_notifications.recipients(campaign_id);

-- Find all campaigns/recipients for a given email address
CREATE INDEX idx_recipients_email
    ON mass_notifications.recipients(email);

-- Find campaigns by date range
CREATE INDEX idx_campaigns_created_at
    ON mass_notifications.campaigns(created_at);

-- Find campaigns by actor (who triggered the send)
CREATE INDEX idx_campaigns_actor
    ON mass_notifications.campaigns(actor);
